### PR TITLE
Add tags to IAM Role

### PR DESCRIPTION
**Pull request by rajgandhi9**
Issue: Add tags to IAM Role

Description:
Adding the user provided tags to the IAM role created by this terraform module

Additional Info:
N/A

### CODE REVIEW

**Comment by rajgandhi9** [comment]
@afiune - Anything else required from my side? Thanks.

**Comment by afiune** [comment]
make it so

**Comment by afiune** [comment]
make it so

**Comment by afiune** [comment]
@rajgandhi9 I don't think you added the `tags` argument in the right resource. 🤔

Could you double-check, please?

**Pull request closed without merging**
